oneri/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('veriokuma/',views.veriokuma, name="veriokuma"),

]

orders/urls.py
from django.urls import path
from . import views

#from .views import category

urlpatterns = [

    path('addtocart/<int:id>',views.addtocart,name='addtocart'),
    path('deletefromcart/<int:id>',views.deletefromcart,name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),


]

yardimseven/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from orders import views as orderviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('yardim.urls')),
    path('accounts/',include('accounts.urls')),
    path('products/',include('products.urls')),
    path('orders/',include('orders.urls')),
    path('oneri/',include('oneri.urls')),

    path('shopcart/', orderviews.shopcart, name='shopcart'),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.forms import ModelForm

from accounts.models import User
# Create your models here.
from products.models import Product


class ShopCart(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    product=models.ForeignKey(Product,on_delete=models.SET_NULL,null=True)
    quantity=models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def price(self):
        return (self.product.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']



class Order(models.Model):
    STATUS= (
        ('New', 'Yeni'),
        ('Accepted', 'Kabul Edildi'),
        ('Preparing', 'Hazırlanıyor'),
        ('OnShipping','Kargolandı'),
        ('Completed', 'Tamamlandı'),
        ('Canceled', 'Iptal'),
    )

    user=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    first_name=models.CharField(max_length=15)
    last_name=models.CharField(max_length=20)
    phone=models.CharField(blank=True, max_length=20)
    total=models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name



class OrderForm(ModelForm):
    class Meta:
        model=Order
        fields=['first_name','last_name','phone']


class OrderProduct(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('Accepted', 'Kabul Edildi'),
        ('Canceled', 'Iptal'),
    )
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    price=models.FloatField()
    amount=models.FloatField()
    status=models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

orders/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect

from django.shortcuts import render, redirect

# Create your views here.
from .models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from products.models import Category,Product
from accounts.models import User



@login_required(login_url='/accounts/login/')
def addtocart(request, id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user
    #------ürün sepette var mı kontrolü----
    checkproduct=ShopCart.objects.filter(product_id=id) #ürün sepette var mı sorgusu
    if checkproduct:
        control = 1  #ürün sepette var
    else:
        control = 0  #ürün sepette yokk

    if request.method == 'POST':   #form post edildiyse
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control==1:  #ürün varsa güncelle
                data=ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else: #ürün yoksa ekle
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, "Ürün başarı ile eklenmiştir. Teşekkür ederiz.")
        return HttpResponseRedirect(url)

    messages.warning(request, "ürünü sepete eklemede bir hata oluştu..")
    return HttpResponseRedirect(url)



@login_required(login_url='/accounts/login/')
def shopcart(request):
    category=Category.objects.all()
    current_user=request.user
    schopcart = ShopCart.objects.filter(user_id=current_user.id)


    total=0
    for rs in schopcart:
        total += rs.product.price * rs.quantity
        total=round(total,2)

    context={
        'schopcart': schopcart,
        'category' : category,
        'total' : total
    }
    return render(request,'orders/shopcart_products.html',context)


@login_required(login_url='/accounts/login/')
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request,"ürün sepetten silindi.")
    return HttpResponseRedirect('/shopcart')

@login_required(login_url='/accounts/login/')
def orderproduct(request):
    category=Category.objects.all()
    current_user=request.user
    schopcart=ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in schopcart:
        total += rs.product.price * rs.quantity
        total = round(total, 2)

    if request.method == 'POST':
        form= OrderForm(request.POST)
        if form.is_valid():
            data=Order()
            data.first_name=form.cleaned_data['first_name']
            data.last_name=form.cleaned_data['last_name']
            data.phone=form.cleaned_data['phone']
            data.user_id=current_user.id
            data.total=total
            data.save()

            schopcart=ShopCart.objects.filter(user_id=current_user.id)
            for rs in schopcart:
                detail=OrderProduct()
                detail.order_id = data.id
                detail.product_id = rs.product.id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                detail.price = rs.product.price
                detail.amount = rs.amount
                detail.save()

                product= Product.objects.get(id=rs.product_id)
                product.amount -=rs.quantity
                product.save()


            ShopCart.objects.filter(user_id=current_user.id).delete()
            messages.success(request,'siparişiniz alındı. Teşekkürler')
            return render(request, 'orders/order_completed.html',{'category':category})
        else:
            messages.warning(request,form.errors)
            return HttpResponseRedirect('/orders/orderproduct')

    form=OrderForm()
    context={
        'schopcart': schopcart,
        'category': category,
        'form' : form,
        'total':total,
    }
    return render(request,'orders/Order_Form.html',context)

templates/orders/Order_Form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{%  load static %}
{% block body %}
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
           <div class="row">
                    <div class="col-sm-6">
                        <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">ALIŞVERİŞ DETAYLARI</div>
                        <div class="p-4">
                          <form action="{% url 'orderproduct' %}" method="post">
                            {% csrf_token %}
                              {{ form|crispy }}
                            <div class="pull-right">
                                <button type="submit" class="btn btn-dark rounded-pill py-2 btn-block">Siparişi Tamamla</button>
                            </div>
                        </form>
                    </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">ÖDEME BİLGİLERİ</div>
                         <div class="p-4">
                             <ul class="list-unstyled mb-4">
                            <p><label for="id_first_name" class="total" >Toplam:</label>
                                <input type="text" name="total" class="form-control form-rounded" readonly value="{{ total }}"></p>
                            <p><label for="id_first_name">Kredi Kart Sahibi</label>
                                <input type="text" name="holder" class="form-control form-rounded"  value=""></p>
                            <p><label for="id_first_name">Kredi Kart Numarası</label>
                                <input type="text" name="number" class="form-control form-rounded"  value=""></p>
                            <p><label for="id_first_name">Son Kullanım Tarihi</label>
                                <input type="text" name="ecpdate" class="form-control form-rounded"  placeholder="mm/yy"></p>
                            <p><label for="id_first_name">Güvenlik Numarası</label>
                                <input type="text" name="secnumber" class="form-control form-rounded"  value=""></p>
                             </ul>
                         </div>
                        </div>
                    </div>

             <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">

          <!-- Shopping cart table -->
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="border-0 bg-light">
                    <div class="p-2 px-3 text-uppercase">Ürün</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Fiyat</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Miktar</div>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                    {% for item in schopcart %}
                              <th scope="row" class="border-0">
                                <div class="p-2">
                                  <img src="{{ item.product.image.url }}" alt="" width="70" class="img-fluid rounded shadow-sm">
                                  <div class="ml-3 d-inline-block align-middle">
                                    <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle">{{ item.product.title }}</a></h5><span class="text-muted font-weight-normal font-italic d-block">{{ item.product.category}}</span>
                                  </div>
                                </div>
                              </th>
                              <td class="border-0 align-middle"><strong>{{item.price}} TL</strong></td>
                              <td class="border-0 align-middle"><strong>{{ item.quantity }}</strong></td>
                            </tr>
                    {% endfor %}
              </tbody>
            </table>
           <div class="col-md-4 ml-auto">
              <div class="p-4">
                <ul class="list-unstyled mb-4">
                  <li class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold"><strong class="text-muted">Toplam</strong>
                    <h5 class="font-weight-bold" class="total"> {{total}} TL</h5>
                  </li>
                </ul>
              </div>
            </div>
              </div>
          <!-- End -->
        </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->

    <!-- /section -->
{% endblock %}

templates/orders/order_completed.html
{% extends 'base.html' %}
{%  block body %}
    <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Sipariş Oluşturuldu.</h3>
                        </div>
                        <hr>
                        <h2>Sayın {{ user.username }}</h2>
                        <hr>
                        <h3>Siparişiniz tamamlanmıştır.</h3>
                        <h3>Teşekkür Ederiz.</h3>
                        <hr>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
{% endblock %}

templates/orders/shopcart_products.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <link rel="icon" href="{% static 'img/icon.png' %}" type="image/png">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<div class="px-4 px-lg-0">
  <div class="pb-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">

          <!-- Shopping cart table -->
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="border-0 bg-light">
                    <div class="p-2 px-3 text-uppercase">Ürün</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">FİYAT</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Adet</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">SepetİMden SİL</div>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                    {% for item in schopcart %}
                              <th scope="row" class="border-0">
                                <div class="p-2">
                                  <img src="{{ item.product.image.url }}" alt="" width="70" class="img-fluid rounded shadow-sm">
                                  <div class="ml-3 d-inline-block align-middle">
                                    <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle">{{ item.product.title }}</a></h5><span class="text-muted font-weight-normal font-italic d-block">{{ item.product.category}}</span>
                                  </div>
                                </div>
                              </th>
                              <td class="border-0 align-middle"><strong>{{item.price}} TL</strong></td>
                              <td class="border-0 align-middle"><strong>{{ item.quantity }}</strong></td>
                              <td class="border-0 align-middle"><a href="/orders/deletefromcart/{{ item.id }}" onclick="return confirm('Silmek istediğine emin misin?')" class="text-dark"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
                            </tr>
                    {% endfor %}
              </tbody>
            </table>
           <div class="col-md-4 ml-auto">
              <div class="p-4">
                <ul class="list-unstyled mb-4">
                  <li class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold"><strong class="text-muted">TOPLAM TUTAR</strong>
                    <h5 class="font-weight-bold" class="total" > {{total}} TL</h5>
                  </li>
                </ul>
                  <a href="{% url 'orderproduct' %}" class="btn btn-dark rounded-pill py-2 btn-block">Onayla</a>
              </div>
            </div>
              </div>
          <!-- End -->

        </div>
      </div>




{% endblock %}